"""Engagement, Diagnostic, Notes, Tasks Table

Revision ID: 4ff8aece5340
Revises: ec0b9b4c6fec
Create Date: 2025-12-10 01:42:35.358597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ff8aece5340'
down_revision = 'ec0b9b4c6fec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=True, comment='Foreign key to firms (NULL for solo advisors)'),
    sa.Column('client_id', sa.UUID(), nullable=False, comment='Foreign key to users (the client account)'),
    sa.Column('primary_advisor_id', sa.UUID(), nullable=False, comment='Foreign key to users (main advisor)'),
    sa.Column('secondary_advisor_ids', sa.ARRAY(sa.UUID()), nullable=True, comment='Array of additional advisor IDs'),
    sa.Column('engagement_name', sa.String(length=255), nullable=False, comment="Project/client name (e.g., 'ABC Corp Growth Strategy')"),
    sa.Column('business_name', sa.String(length=255), nullable=True, comment="Client's business name"),
    sa.Column('industry', sa.String(length=100), nullable=True, comment='Business industry'),
    sa.Column('description', sa.Text(), nullable=True, comment='Engagement description/notes'),
    sa.Column('tool', sa.String(length=100), nullable=True, comment='Selected tool for the engagement'),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False, comment='active, paused, completed, archived'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_engagements_client_id'), 'engagements', ['client_id'], unique=False)
    op.create_index(op.f('ix_engagements_firm_id'), 'engagements', ['firm_id'], unique=False)
    op.create_index(op.f('ix_engagements_primary_advisor_id'), 'engagements', ['primary_advisor_id'], unique=False)
    op.create_index(op.f('ix_engagements_status'), 'engagements', ['status'], unique=False)
    op.create_table('diagnostics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('completed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False, comment='draft, in_progress, processing, completed, archived'),
    sa.Column('diagnostic_type', sa.String(length=100), server_default='business_health_assessment', nullable=False),
    sa.Column('diagnostic_version', sa.String(length=20), server_default='1.0', nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='All 200 questions with their structure (from JSON file)'),
    sa.Column('user_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="User's answers to all questions"),
    sa.Column('scoring_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Question-level and module-level scores'),
    sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='GPT-generated insights, recommendations, commentary'),
    sa.Column('module_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='The 8 module scores (M1-M8) with details'),
    sa.Column('overall_score', sa.Numeric(precision=3, scale=1), nullable=True, comment='Overall diagnostic score (0-5, 1 decimal place)'),
    sa.Column('report_url', sa.Text(), nullable=True, comment='S3/storage URL for generated PDF report'),
    sa.Column('report_html', sa.Text(), nullable=True, comment='HTML version of the report (optional)'),
    sa.Column('tasks_generated_count', sa.Integer(), server_default='0', nullable=True, comment='Number of tasks generated from this diagnostic'),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True, comment='AI model used for analysis (e.g., gpt-4-turbo)'),
    sa.Column('ai_tokens_used', sa.Integer(), nullable=True, comment='Total tokens used in AI processing'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='When user started filling it out'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='When user submitted it'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_diagnostics_completed_by_user_id'), 'diagnostics', ['completed_by_user_id'], unique=False)
    op.create_index(op.f('ix_diagnostics_created_by_user_id'), 'diagnostics', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_diagnostics_engagement_id'), 'diagnostics', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_diagnostics_status'), 'diagnostics', ['status'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('diagnostic_id', sa.UUID(), nullable=True, comment='Optional: if note references a specific diagnostic'),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True, comment='Optional note title'),
    sa.Column('content', sa.Text(), nullable=False, comment='Note content/body'),
    sa.Column('note_type', sa.String(length=50), server_default='general', nullable=False, comment='general, meeting, observation, decision, progress_update'),
    sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False, comment='Whether note is pinned to top'),
    sa.Column('visibility', sa.String(length=50), server_default='all', nullable=False, comment='all, advisor_only, client_only'),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True, comment='Array of tags for categorization'),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of attachment metadata (file URLs, names, types)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diagnostic_id'], ['diagnostics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_notes_author_id'), 'notes', ['author_id'], unique=False)
    op.create_index(op.f('ix_notes_created_at'), 'notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_notes_diagnostic_id'), 'notes', ['diagnostic_id'], unique=False)
    op.create_index(op.f('ix_notes_engagement_id'), 'notes', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_notes_note_type'), 'notes', ['note_type'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('diagnostic_id', sa.UUID(), nullable=True, comment='If auto-generated from diagnostic'),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Task title/name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed task description'),
    sa.Column('task_type', sa.String(length=50), server_default='manual', nullable=False, comment='manual, diagnostic_generated'),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False, comment='pending, in_progress, completed, cancelled'),
    sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False, comment='low, medium, high, urgent'),
    sa.Column('priority_rank', sa.Integer(), nullable=True, comment='Priority rank from AI (1 = highest priority)'),
    sa.Column('module_reference', sa.String(length=10), nullable=True, comment='Module reference from diagnostic (e.g., M1, M2, M3)'),
    sa.Column('impact_level', sa.String(length=20), nullable=True, comment='Impact level: low, medium, high'),
    sa.Column('effort_level', sa.String(length=20), nullable=True, comment='Effort level: low, medium, high'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='Task due date'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='When task was completed'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diagnostic_id'], ['diagnostics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to_user_id'), 'tasks', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_by_user_id'), 'tasks', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_diagnostic_id'), 'tasks', ['diagnostic_id'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_engagement_id'), 'tasks', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_engagement_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_diagnostic_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_notes_note_type'), table_name='notes')
    op.drop_index(op.f('ix_notes_engagement_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_diagnostic_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_created_at'), table_name='notes')
    op.drop_index(op.f('ix_notes_author_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_diagnostics_status'), table_name='diagnostics')
    op.drop_index(op.f('ix_diagnostics_engagement_id'), table_name='diagnostics')
    op.drop_index(op.f('ix_diagnostics_created_by_user_id'), table_name='diagnostics')
    op.drop_index(op.f('ix_diagnostics_completed_by_user_id'), table_name='diagnostics')
    op.drop_table('diagnostics')
    op.drop_index(op.f('ix_engagements_status'), table_name='engagements')
    op.drop_index(op.f('ix_engagements_primary_advisor_id'), table_name='engagements')
    op.drop_index(op.f('ix_engagements_firm_id'), table_name='engagements')
    op.drop_index(op.f('ix_engagements_client_id'), table_name='engagements')
    op.drop_table('engagements')
    # ### end Alembic commands ###



