"""tag_addition_for_advisor

Revision ID: 5519ec0f63ad
Revises: c457376982ac
Create Date: 2025-12-31 16:42:44.326272

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5519ec0f63ad'
down_revision = 'c457376982ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnostics', sa.Column('tag', sa.String(length=255), nullable=True, comment='Document tag for organization (advisor-only)'))
    op.add_column('media', sa.Column('tag', sa.String(length=255), nullable=True, comment='Document tag for organization (advisor-only)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'tag')
    op.drop_column('diagnostics', 'tag')
    # ### end Alembic commands ###



