"""first_name last_name

Revision ID: 662a7acdc7ea
Revises: 5519ec0f63ad
Create Date: 2026-01-01 17:38:49.837573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.models.user import UserRoleType
# revision identifiers, used by Alembic.
revision = '662a7acdc7ea'
down_revision = '5519ec0f63ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=True, comment="User's first name"))
    op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=True, comment="User's last name"))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADVISOR', 'CLIENT', 'ADMIN', 'SUPER_ADMIN', 'firm_admin', 'firm_advisor', name='userrole'),
               type_=UserRoleType(length=50),
               existing_comment='User role (advisor, client, admin, super_admin, firm_admin, firm_advisor)',
               existing_nullable=False)
    op.drop_column('users', 'family_name')
    op.drop_column('users', 'given_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('given_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment="User's first/given name"))
    op.add_column('users', sa.Column('family_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment="User's last/family name"))
    op.alter_column('users', 'role',
               existing_type=UserRoleType(length=50),
               type_=postgresql.ENUM('ADVISOR', 'CLIENT', 'ADMIN', 'SUPER_ADMIN', 'firm_admin', 'firm_advisor', name='userrole'),
               existing_comment='User role (advisor, client, admin, super_admin, firm_admin, firm_advisor)',
               existing_nullable=False)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###



