"""Add firm and subscription tables

Revision ID: 686ebbdaca62
Revises: 6d6185e73276
Create Date: 2025-12-19 14:57:00.870762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '686ebbdaca62'
down_revision = '6d6185e73276'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_openai_file_id'), table_name='media')
    op.drop_index(op.f('ix_media_user_id'), table_name='media')
    op.drop_table('media')
    op.drop_table('diagnostic_media')
    op.create_foreign_key(None, 'engagements', 'firms', ['firm_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'firms', ['id'])
    op.create_unique_constraint(None, 'subscriptions', ['id'])
    op.add_column('users', sa.Column('firm_id', sa.UUID(), nullable=True, comment='Foreign key to firms (NULL for solo advisors/clients)'))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADVISOR', 'CLIENT', 'ADMIN', 'SUPER_ADMIN', name='userrole'),
               comment='User role (advisor, client, admin, super_admin, firm_admin, firm_advisor)',
               existing_comment='User role (advisor, client, admin, super_admin)',
               existing_nullable=False)
    op.create_index(op.f('ix_users_firm_id'), 'users', ['firm_id'], unique=False)
    op.create_foreign_key(None, 'users', 'firms', ['firm_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_firm_id'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADVISOR', 'CLIENT', 'ADMIN', 'SUPER_ADMIN', name='userrole'),
               comment='User role (advisor, client, admin, super_admin)',
               existing_comment='User role (advisor, client, admin, super_admin, firm_admin, firm_advisor)',
               existing_nullable=False)
    op.drop_column('users', 'firm_id')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_constraint(None, 'firms', type_='unique')
    op.drop_constraint(None, 'engagements', type_='foreignkey')
    op.create_table('diagnostic_media',
    sa.Column('diagnostic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('media_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_id'], ['diagnostics.id'], name=op.f('diagnostic_media_diagnostic_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('diagnostic_media_media_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('diagnostic_id', 'media_id', name=op.f('diagnostic_media_pkey'))
    )
    op.create_table('media',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Original filename'),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False, comment='Storage path (local or S3)'),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True, comment='File size in bytes'),
    sa.Column('file_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='MIME type'),
    sa.Column('file_extension', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='File extension (pdf, jpg, etc.)'),
    sa.Column('openai_file_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='OpenAI file ID for GPT analysis'),
    sa.Column('openai_purpose', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='OpenAI file purpose (assistants, vision, etc.)'),
    sa.Column('openai_uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='When uploaded to OpenAI'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='User-provided description'),
    sa.Column('question_field_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Which diagnostic question this file answers'),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Soft delete timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('media_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('media_pkey'))
    )
    op.create_index(op.f('ix_media_user_id'), 'media', ['user_id'], unique=False)
    op.create_index(op.f('ix_media_openai_file_id'), 'media', ['openai_file_id'], unique=True)
    # ### end Alembic commands ###



