"""added_users_bio

Revision ID: 6d6185e73276
Revises: 79dc61b1e153
Create Date: 2025-12-16 14:53:04.213002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6185e73276'
down_revision = '79dc61b1e153'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True, comment='Short biography or profile description'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###



