"""Media table

Revision ID: 72c3acd59594
Revises: 6d6185e73276
Create Date: 2025-12-18 13:07:42.789006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c3acd59594'
down_revision = '6d6185e73276'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table already exists (for cases where table was created manually)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'media' not in tables:
        op.create_table('media',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('user_id', sa.UUID(), nullable=False),
            sa.Column('file_name', sa.String(length=255), nullable=False, comment='Original filename'),
            sa.Column('file_path', sa.Text(), nullable=False, comment='Storage path (local or S3)'),
            sa.Column('file_size', sa.Integer(), nullable=True, comment='File size in bytes'),
            sa.Column('file_type', sa.String(length=100), nullable=True, comment='MIME type'),
            sa.Column('file_extension', sa.String(length=20), nullable=True, comment='File extension (pdf, jpg, etc.)'),
            sa.Column('openai_file_id', sa.String(length=255), nullable=True, comment='OpenAI file ID for GPT analysis'),
            sa.Column('openai_purpose', sa.String(length=50), nullable=True, comment='OpenAI file purpose (assistants, vision, etc.)'),
            sa.Column('openai_uploaded_at', sa.DateTime(), nullable=True, comment='When uploaded to OpenAI'),
            sa.Column('description', sa.Text(), nullable=True, comment='User-provided description'),
            sa.Column('question_field_name', sa.String(length=255), nullable=True, comment='Which diagnostic question this file answers'),
            sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
            sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
            sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('id')
        )
        op.create_index(op.f('ix_media_openai_file_id'), 'media', ['openai_file_id'], unique=True)
        op.create_index(op.f('ix_media_user_id'), 'media', ['user_id'], unique=False)
    
    if 'diagnostic_media' not in tables:
        op.create_table('diagnostic_media',
            sa.Column('diagnostic_id', sa.UUID(), nullable=False),
            sa.Column('media_id', sa.UUID(), nullable=False),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
            sa.ForeignKeyConstraint(['diagnostic_id'], ['diagnostics.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('diagnostic_id', 'media_id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnostic_media')
    op.drop_index(op.f('ix_media_user_id'), table_name='media')
    op.drop_index(op.f('ix_media_openai_file_id'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###



