"""notes, tasks, engagments

Revision ID: 79dc61b1e153
Revises: 4ff8aece5340
Create Date: 2025-12-12 11:18:49.358134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79dc61b1e153'
down_revision = '4ff8aece5340'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'diagnostics', ['id'])
    op.create_unique_constraint(None, 'engagements', ['id'])
    op.add_column('notes', sa.Column('task_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_notes_task_id'), 'notes', ['task_id'], unique=False)
    op.create_unique_constraint(None, 'notes', ['id'])
    op.create_foreign_key(None, 'notes', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'tasks', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='unique')
    op.drop_index(op.f('ix_notes_task_id'), table_name='notes')
    op.drop_column('notes', 'task_id')
    op.drop_constraint(None, 'engagements', type_='unique')
    op.drop_constraint(None, 'diagnostics', type_='unique')
    # ### end Alembic commands ###



