"""add_password_field

Revision ID: 7a0c72f39586
Revises: ebb9f06268c6
Create Date: 2025-12-23 14:49:49.051646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0c72f39586'
down_revision = 'ebb9f06268c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_firm_id'), table_name='subscriptions')
    op.drop_constraint(op.f('subscriptions_firm_id_fkey'), 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'firm_id')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='Hashed password for email/password authentication'))
    op.alter_column('users', 'auth0_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment='Auth0 user ID (sub claim from token). NULL for email/password users.',
               existing_comment='Auth0 user ID (sub claim from token)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth0_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment='Auth0 user ID (sub claim from token)',
               existing_comment='Auth0 user ID (sub claim from token). NULL for email/password users.')
    op.drop_column('users', 'hashed_password')
    op.add_column('subscriptions', sa.Column('firm_id', sa.UUID(), autoincrement=False, nullable=False, comment='Foreign key to firms (one subscription per firm)'))
    op.create_foreign_key(op.f('subscriptions_firm_id_fkey'), 'subscriptions', 'firms', ['firm_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_subscriptions_firm_id'), 'subscriptions', ['firm_id'], unique=True)
    # ### end Alembic commands ###



