"""add_password_field

Revision ID: 7a0c72f39586
Revises: ebb9f06268c6
Create Date: 2025-12-23 14:49:49.051646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0c72f39586'
down_revision = 'ebb9f06268c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if subscriptions table exists and has the firm_id column
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'subscriptions' in tables:
        columns = [col['name'] for col in inspector.get_columns('subscriptions')]
        if 'firm_id' in columns:
            # Check if index exists
            indexes = [idx['name'] for idx in inspector.get_indexes('subscriptions')]
            if 'ix_subscriptions_firm_id' in indexes:
                op.drop_index(op.f('ix_subscriptions_firm_id'), table_name='subscriptions')
            
            # Check if constraint exists
            constraints = [fk['name'] for fk in inspector.get_foreign_keys('subscriptions')]
            if 'subscriptions_firm_id_fkey' in constraints:
                op.drop_constraint(op.f('subscriptions_firm_id_fkey'), 'subscriptions', type_='foreignkey')
            
            op.drop_column('subscriptions', 'firm_id')
    
    # Add hashed_password to users table (this is the important part)
    columns = [col['name'] for col in inspector.get_columns('users')]
    if 'hashed_password' not in columns:
        op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='Hashed password for email/password authentication'))
    
    # Make auth0_id nullable if it's not already
    auth0_col = next((col for col in inspector.get_columns('users') if col['name'] == 'auth0_id'), None)
    if auth0_col and auth0_col.get('nullable') is False:
        op.alter_column('users', 'auth0_id',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True,
                   comment='Auth0 user ID (sub claim from token). NULL for email/password users.',
                   existing_comment='Auth0 user ID (sub claim from token)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Revert users table changes
    columns = [col['name'] for col in inspector.get_columns('users')]
    auth0_col = next((col for col in inspector.get_columns('users') if col['name'] == 'auth0_id'), None)
    if auth0_col and auth0_col.get('nullable') is True:
        op.alter_column('users', 'auth0_id',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=False,
                   comment='Auth0 user ID (sub claim from token)',
                   existing_comment='Auth0 user ID (sub claim from token). NULL for email/password users.')
    
    if 'hashed_password' in columns:
        op.drop_column('users', 'hashed_password')
    
    # Revert subscriptions table changes (only if subscriptions table exists)
    tables = inspector.get_table_names()
    if 'subscriptions' in tables:
        columns = [col['name'] for col in inspector.get_columns('subscriptions')]
        if 'firm_id' not in columns:
            op.add_column('subscriptions', sa.Column('firm_id', sa.UUID(), autoincrement=False, nullable=False, comment='Foreign key to firms (one subscription per firm)'))
            op.create_foreign_key(op.f('subscriptions_firm_id_fkey'), 'subscriptions', 'firms', ['firm_id'], ['id'], ondelete='CASCADE')
            op.create_index(op.f('ix_subscriptions_firm_id'), 'subscriptions', ['firm_id'], unique=True)
    # ### end Alembic commands ###



