"""add bba task planner columns

Revision ID: a8d3b2d2caf9
Revises: 4a3c2b1d0e9f
Create Date: 2026-02-11 14:03:59.512306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8d3b2d2caf9'
down_revision = '4a3c2b1d0e9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Originally a raw autogenerate dump. Every destructive/creative operation is
    # now guarded by an inspector check, matching the rest of this migration set,
    # because databases legitimately differ on which of these already exist.
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()

    def _has_unique_on_id(table):
        return any(uc['column_names'] == ['id']
                   for uc in inspector.get_unique_constraints(table))

    for table in ('advisor_client', 'bba', 'conversations', 'impersonation_sessions', 'messages'):
        if table in tables and not _has_unique_on_id(table):
            op.create_unique_constraint(None, table, ['id'])

    bba_columns = [col['name'] for col in inspector.get_columns('bba')] if 'bba' in tables else []
    if 'bba' in tables:
        if 'task_planner_settings' not in bba_columns:
            op.add_column('bba', sa.Column('task_planner_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Phase 2 task planner context: lead/support advisors, advisor_count, max_hours_per_month, start_month, start_year'))
        if 'task_planner_tasks' not in bba_columns:
            op.add_column('bba', sa.Column('task_planner_tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Phase 2 generated task rows used for Excel export. Each row matches the Excel columns: Rec #, Recommendation, Owner, Task, Advisor Hrs, Advisor, Status, Notes, Timing.'))
        if 'task_planner_summary' not in bba_columns:
            op.add_column('bba', sa.Column('task_planner_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Phase 2 summary data including total BBA hours, per-month hours, and any capacity warnings.'))

    op.alter_column('engagements', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='Whether the engagement has been soft deleted',
               existing_nullable=False,
               existing_server_default=sa.text('false'))

    if 'firms' in tables:
        eng_fks = [fk['referred_table'] for fk in inspector.get_foreign_keys('engagements')]
        if 'firms' not in eng_fks:
            op.create_foreign_key(None, 'engagements', 'firms', ['firm_id'], ['id'], ondelete='SET NULL')

    if 'subscriptions' in tables:
        sub_indexes = [idx['name'] for idx in inspector.get_indexes('subscriptions')]
        if 'ix_subscriptions_firm_id' in sub_indexes:
            op.drop_index(op.f('ix_subscriptions_firm_id'), table_name='subscriptions')
        sub_fks = [fk['name'] for fk in inspector.get_foreign_keys('subscriptions')]
        if 'subscriptions_firm_id_fkey' in sub_fks:
            op.drop_constraint(op.f('subscriptions_firm_id_fkey'), 'subscriptions', type_='foreignkey')
        sub_columns = [col['name'] for col in inspector.get_columns('subscriptions')]
        for col in ('current_period_end', 'cancel_at_period_end', 'current_period_start',
                    'firm_id', 'cancelled_at'):
            if col in sub_columns:
                op.drop_column('subscriptions', col)

    op.alter_column('tasks', 'assigned_to_user_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               comment='Array of user IDs assigned to this task (for multiple assignments, e.g., all advisors in engagement)',
               existing_nullable=True)
    # add_assigned_to_user_ids_to_tasks already creates this index (as GIN); only
    # create it here if that migration has not supplied it.
    task_indexes = [idx['name'] for idx in inspector.get_indexes('tasks')]
    if 'ix_tasks_assigned_to_user_ids' not in task_indexes:
        op.create_index(op.f('ix_tasks_assigned_to_user_ids'), 'tasks', ['assigned_to_user_ids'], unique=False)

    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='Whether the user has been soft deleted',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'firm_id',
               existing_type=sa.UUID(),
               comment='Foreign key to firms table (for firm_admin and firm_advisor users)',
               existing_nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'firm_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Foreign key to firms table (for firm_admin and firm_advisor users)',
               existing_nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether the user has been soft deleted',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_tasks_assigned_to_user_ids'), table_name='tasks')
    op.alter_column('tasks', 'assigned_to_user_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               comment=None,
               existing_comment='Array of user IDs assigned to this task (for multiple assignments, e.g., all advisors in engagement)',
               existing_nullable=True)
    op.add_column('subscriptions', sa.Column('cancelled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='When subscription was cancelled'))
    op.add_column('subscriptions', sa.Column('firm_id', sa.UUID(), autoincrement=False, nullable=True, comment='Foreign key to firms (nullable - subscription can exist without a firm)'))
    op.add_column('subscriptions', sa.Column('current_period_start', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False, comment='Start of current billing period'))
    op.add_column('subscriptions', sa.Column('cancel_at_period_end', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Whether subscription will cancel at period end'))
    op.add_column('subscriptions', sa.Column('current_period_end', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False, comment='End of current billing period'))
    op.create_foreign_key(op.f('subscriptions_firm_id_fkey'), 'subscriptions', 'firms', ['firm_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_subscriptions_firm_id'), 'subscriptions', ['firm_id'], unique=False)
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'impersonation_sessions', type_='unique')
    op.drop_constraint(None, 'engagements', type_='foreignkey')
    op.alter_column('engagements', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether the engagement has been soft deleted',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'conversations', type_='unique')
    op.drop_constraint(None, 'bba', type_='unique')
    op.drop_column('bba', 'task_planner_summary')
    op.drop_column('bba', 'task_planner_tasks')
    op.drop_column('bba', 'task_planner_settings')
    op.drop_constraint(None, 'advisor_client', type_='unique')
    # ### end Alembic commands ###



