"""add bba task planner columns

Revision ID: a8d3b2d2caf9
Revises: 4a3c2b1d0e9f
Create Date: 2026-02-11 14:03:59.512306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8d3b2d2caf9'
down_revision = '4a3c2b1d0e9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'advisor_client', ['id'])
    op.add_column('bba', sa.Column('task_planner_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Phase 2 task planner context: lead/support advisors, advisor_count, max_hours_per_month, start_month, start_year'))
    op.add_column('bba', sa.Column('task_planner_tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Phase 2 generated task rows used for Excel export. Each row matches the Excel columns: Rec #, Recommendation, Owner, Task, Advisor Hrs, Advisor, Status, Notes, Timing.'))
    op.add_column('bba', sa.Column('task_planner_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Phase 2 summary data including total BBA hours, per-month hours, and any capacity warnings.'))
    op.create_unique_constraint(None, 'bba', ['id'])
    op.create_unique_constraint(None, 'conversations', ['id'])
    op.alter_column('engagements', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='Whether the engagement has been soft deleted',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(None, 'engagements', 'firms', ['firm_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'impersonation_sessions', ['id'])
    op.create_unique_constraint(None, 'messages', ['id'])
    op.drop_index(op.f('ix_subscriptions_firm_id'), table_name='subscriptions')
    op.drop_constraint(op.f('subscriptions_firm_id_fkey'), 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'current_period_end')
    op.drop_column('subscriptions', 'cancel_at_period_end')
    op.drop_column('subscriptions', 'current_period_start')
    op.drop_column('subscriptions', 'firm_id')
    op.drop_column('subscriptions', 'cancelled_at')
    op.alter_column('tasks', 'assigned_to_user_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               comment='Array of user IDs assigned to this task (for multiple assignments, e.g., all advisors in engagement)',
               existing_nullable=True)
    op.create_index(op.f('ix_tasks_assigned_to_user_ids'), 'tasks', ['assigned_to_user_ids'], unique=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='Whether the user has been soft deleted',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'firm_id',
               existing_type=sa.UUID(),
               comment='Foreign key to firms table (for firm_admin and firm_advisor users)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'firm_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Foreign key to firms table (for firm_admin and firm_advisor users)',
               existing_nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether the user has been soft deleted',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_tasks_assigned_to_user_ids'), table_name='tasks')
    op.alter_column('tasks', 'assigned_to_user_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               comment=None,
               existing_comment='Array of user IDs assigned to this task (for multiple assignments, e.g., all advisors in engagement)',
               existing_nullable=True)
    op.add_column('subscriptions', sa.Column('cancelled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='When subscription was cancelled'))
    op.add_column('subscriptions', sa.Column('firm_id', sa.UUID(), autoincrement=False, nullable=True, comment='Foreign key to firms (nullable - subscription can exist without a firm)'))
    op.add_column('subscriptions', sa.Column('current_period_start', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False, comment='Start of current billing period'))
    op.add_column('subscriptions', sa.Column('cancel_at_period_end', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Whether subscription will cancel at period end'))
    op.add_column('subscriptions', sa.Column('current_period_end', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False, comment='End of current billing period'))
    op.create_foreign_key(op.f('subscriptions_firm_id_fkey'), 'subscriptions', 'firms', ['firm_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_subscriptions_firm_id'), 'subscriptions', ['firm_id'], unique=False)
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'impersonation_sessions', type_='unique')
    op.drop_constraint(None, 'engagements', type_='foreignkey')
    op.alter_column('engagements', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether the engagement has been soft deleted',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'conversations', type_='unique')
    op.drop_constraint(None, 'bba', type_='unique')
    op.drop_column('bba', 'task_planner_summary')
    op.drop_column('bba', 'task_planner_tasks')
    op.drop_column('bba', 'task_planner_settings')
    op.drop_constraint(None, 'advisor_client', type_='unique')
    # ### end Alembic commands ###



