"""task table - module_reference

Revision ID: b2465e2f298a
Revises: 72c3acd59594
Create Date: 2025-12-18 13:22:07.178143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2465e2f298a'
down_revision = '72c3acd59594'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'media', ['id'])
    op.alter_column('tasks', 'module_reference',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_comment='Module reference from diagnostic (e.g., M1, M2, M3)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'module_reference',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_comment='Module reference from diagnostic (e.g., M1, M2, M3)',
               existing_nullable=True)
    op.drop_constraint(None, 'media', type_='unique')
    # ### end Alembic commands ###



