"""conversations and messages

Revision ID: c457376982ac
Revises: b2465e2f298a
Create Date: 2025-12-29 16:01:54.359111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.models.user import UserRoleType
# revision identifiers, used by Alembic.
revision = 'c457376982ac'
down_revision = 'b2465e2f298a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), server_default='general', nullable=False, comment='general, diagnostic, finance, legal, operations, etc.'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='Optional conversation title'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_conversations_category'), 'conversations', ['category'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='user or assistant'),
    sa.Column('message', sa.Text(), nullable=False, comment='The message content'),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Raw GPT response data'),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata (tokens, model, etc.)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    op.add_column('diagnostics', sa.Column('conversation_id', sa.UUID(), nullable=True, comment='Linked conversation for chat about this diagnostic'))
    op.create_index(op.f('ix_diagnostics_conversation_id'), 'diagnostics', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'diagnostics', 'conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=20),
               comment='low, medium, high, critical',
               existing_comment='low, medium, high, urgent',
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADVISOR', 'CLIENT', 'ADMIN', 'SUPER_ADMIN', name='userrole'),
               type_=UserRoleType(length=50),
               comment='User role (advisor, client, admin, super_admin, firm_admin, firm_advisor)',
               existing_comment='User role (advisor, client, admin, super_admin)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=UserRoleType(length=50),
               type_=postgresql.ENUM('ADVISOR', 'CLIENT', 'ADMIN', 'SUPER_ADMIN', name='userrole'),
               comment='User role (advisor, client, admin, super_admin)',
               existing_comment='User role (advisor, client, admin, super_admin, firm_admin, firm_advisor)',
               existing_nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=20),
               comment='low, medium, high, urgent',
               existing_comment='low, medium, high, critical',
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.drop_constraint(None, 'diagnostics', type_='foreignkey')
    op.drop_index(op.f('ix_diagnostics_conversation_id'), table_name='diagnostics')
    op.drop_column('diagnostics', 'conversation_id')
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_category'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###



