"""drop redundant unique constraints and repair strategy_workbooks status index

Revision ID: drop_redundant_uniques
Revises: merge_pd_scorecard_cleanup
Create Date: 2026-08-25

Hand-written, not autogenerated. Two changes:

1. Drop 13 unique constraints that duplicate a guarantee already enforced:
   12 x <table>_id_key UNIQUE (id), covered by each table's primary key, and
   document_templates_file_name_key, covered by ix_document_templates_file_name
   (left in place).

   A constraint is skipped where a foreign key has been bound to its index
   rather than to the primary key — dropping it there raises
   DependentObjectsStillExist. Local and production have no such bindings, so
   all 13 drop; the shared staging database has 45 across 6 tables and keeps
   those 6. The duplicated guarantee holds in both cases.

2. Create ix_strategy_workbooks_status. add_strategy_workbooks_table.py checks a
   table snapshot taken before its own create_table, so the index branch never
   fires on a from-scratch database and such environments never get the index.

Every operation is guarded, so this is a no-op wherever the state already
matches. Column and table comments are deliberately untouched.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'drop_redundant_uniques'
down_revision = 'merge_pd_scorecard_cleanup'
branch_labels = None
depends_on = None


# (table, canonical constraint name, columns it covers)
REDUNDANT_UNIQUES = [
    ("advisor_client", "advisor_client_id_key", ["id"]),
    ("bba", "bba_id_key", ["id"]),
    ("conversations", "conversations_id_key", ["id"]),
    ("diagnostics", "diagnostics_id_key", ["id"]),
    ("engagements", "engagements_id_key", ["id"]),
    ("impersonation_sessions", "impersonation_sessions_id_key", ["id"]),
    ("media", "media_id_key", ["id"]),
    ("messages", "messages_id_key", ["id"]),
    ("notes", "notes_id_key", ["id"]),
    ("strategy_workbooks", "strategy_workbooks_id_key", ["id"]),
    ("tasks", "tasks_id_key", ["id"]),
    ("users", "users_id_key", ["id"]),
    ("document_templates", "document_templates_file_name_key", ["file_name"]),
]


def _find_unique(inspector, table, columns):
    """Return the unique constraint covering these columns, by whatever name.

    SQLAlchemy reports primary keys separately, so an ('id',) match can only
    ever find the redundant constraint. Returns None if the table or the
    constraint is absent.
    """
    if table not in inspector.get_table_names():
        return None
    for uc in inspector.get_unique_constraints(table):
        if list(uc["column_names"]) == list(columns):
            return uc["name"]
    return None


def _dependent_fks(conn, constraint_name):
    """Foreign keys Postgres has bound to this constraint's index.

    A foreign key targets whichever unique index satisfied it at creation time,
    which is not always the primary key. Where it landed on the redundant
    constraint instead, DROP CONSTRAINT raises DependentObjectsStillExist.
    """
    return [
        row[0]
        for row in conn.execute(
            sa.text(
                """
                SELECT c.conname
                FROM pg_depend d
                JOIN pg_constraint c ON c.oid = d.objid AND c.contype = 'f'
                JOIN pg_class ci ON ci.oid = d.refobjid
                WHERE d.refclassid = 'pg_class'::regclass
                  AND ci.relname = :name
                """
            ),
            {"name": constraint_name},
        )
    ]


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 1. drop the redundant constraints, by discovered name
    for table, _name, columns in REDUNDANT_UNIQUES:
        found = _find_unique(inspector, table, columns)
        if not found:
            continue
        # Leave the constraint in place where a foreign key depends on its
        # index. It is still redundant, but dropping it would either fail or
        # force 45-odd foreign keys to be rebuilt; the guarantee it duplicates
        # is unaffected either way.
        dependents = _dependent_fks(conn, found)
        if dependents:
            print(
                f"drop_redundant_uniques: skipping {found} on {table}; "
                f"{len(dependents)} foreign key(s) depend on it "
                f"({', '.join(sorted(dependents)[:3])}"
                f"{', ...' if len(dependents) > 3 else ''})"
            )
            continue
        op.drop_constraint(found, table, type_="unique")

    # 2. repair the index missing on from-scratch databases
    if "strategy_workbooks" in inspector.get_table_names():
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_strategy_workbooks_status "
            "ON strategy_workbooks (status)"
        )


def downgrade() -> None:
    inspector = sa.inspect(op.get_bind())

    for table, name, columns in REDUNDANT_UNIQUES:
        if table not in inspector.get_table_names():
            continue
        if _find_unique(inspector, table, columns) is None:
            op.create_unique_constraint(name, table, columns)

    # ix_strategy_workbooks_status is intentionally left in place: upgrade() may
    # have been a no-op for it, so dropping here would remove an index that
    # predates this revision. add_strategy_workbooks_table.py owns its lifecycle.
