"""conversations and messages

Revision ID: e3edf1331520
Revises: b2465e2f298a
Create Date: 2025-12-26 14:45:51.206199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3edf1331520'
down_revision = 'b2465e2f298a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'conversations', ['id'])
    op.add_column('diagnostics', sa.Column('conversation_id', sa.UUID(), nullable=True, comment='Linked conversation for chat about this diagnostic'))
    op.create_index(op.f('ix_diagnostics_conversation_id'), 'diagnostics', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'diagnostics', 'conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'messages', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'diagnostics', type_='foreignkey')
    op.drop_index(op.f('ix_diagnostics_conversation_id'), table_name='diagnostics')
    op.drop_column('diagnostics', 'conversation_id')
    op.drop_constraint(None, 'conversations', type_='unique')
    # ### end Alembic commands ###



