"""added subscription and client_id

Revision ID: ebb9f06268c6
Revises: 2eb0a6a49983
Create Date: 2025-12-22 11:36:44.559553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb9f06268c6'
down_revision = '2eb0a6a49983'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firms', sa.Column('clients', sa.ARRAY(sa.UUID()), nullable=True, comment='Array of client user IDs associated with this firm'))
    op.alter_column('firms', 'subscription_id',
               existing_type=sa.UUID(),
               comment='Foreign key to subscriptions',
               existing_nullable=True)
    op.create_unique_constraint(None, 'firms', ['id'])
    op.create_unique_constraint(None, 'subscriptions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_constraint(None, 'firms', type_='unique')
    op.alter_column('firms', 'subscription_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Foreign key to subscriptions',
               existing_nullable=True)
    op.drop_column('firms', 'clients')
    # ### end Alembic commands ###



