"""added subscription and client_id

Revision ID: ebb9f06268c6
Revises: 2eb0a6a49983
Create Date: 2025-12-22 11:36:44.559553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb9f06268c6'
down_revision = '2eb0a6a49983'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if firms table exists before trying to modify it
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'firms' in tables:
        columns = [col['name'] for col in inspector.get_columns('firms')]
        if 'clients' not in columns:
            op.add_column('firms', sa.Column('clients', sa.ARRAY(sa.UUID()), nullable=True, comment='Array of client user IDs associated with this firm'))
        if 'subscription_id' in columns:
            op.alter_column('firms', 'subscription_id',
                       existing_type=sa.UUID(),
                       comment='Foreign key to subscriptions',
                       existing_nullable=True)
        # Check if constraint already exists
        constraints = [c['name'] for c in inspector.get_unique_constraints('firms')]
        if not any('id' in str(c) for c in constraints):
            op.create_unique_constraint(None, 'firms', ['id'])
    
    if 'subscriptions' in tables:
        constraints = [c['name'] for c in inspector.get_unique_constraints('subscriptions')]
        if not any('id' in str(c) for c in constraints):
            op.create_unique_constraint(None, 'subscriptions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'subscriptions' in tables:
        try:
            op.drop_constraint(None, 'subscriptions', type_='unique')
        except:
            pass
    
    if 'firms' in tables:
        columns = [col['name'] for col in inspector.get_columns('firms')]
        try:
            op.drop_constraint(None, 'firms', type_='unique')
        except:
            pass
        if 'subscription_id' in columns:
            op.alter_column('firms', 'subscription_id',
                       existing_type=sa.UUID(),
                       comment=None,
                       existing_comment='Foreign key to subscriptions',
                       existing_nullable=True)
        if 'clients' in columns:
            op.drop_column('firms', 'clients')
    # ### end Alembic commands ###



