"""Users Table

Revision ID: ec0b9b4c6fec
Revises: 
Create Date: 2025-12-04 17:24:03.733731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0b9b4c6fec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the user'),
    sa.Column('auth0_id', sa.String(length=255), nullable=False, comment='Auth0 user ID (sub claim from token)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address"),
    sa.Column('name', sa.String(length=255), nullable=True, comment="User's full name"),
    sa.Column('given_name', sa.String(length=255), nullable=True, comment="User's first/given name"),
    sa.Column('family_name', sa.String(length=255), nullable=True, comment="User's last/family name"),
    sa.Column('nickname', sa.String(length=255), nullable=True, comment="User's nickname"),
    sa.Column('picture', sa.Text(), nullable=True, comment="URL to user's profile picture"),
    sa.Column('email_verified', sa.Boolean(), nullable=False, comment='Whether the email has been verified'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the user account is active'),
    sa.Column('role', sa.Enum('ADVISOR', 'CLIENT', 'ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False, comment='User role (advisor, client, admin, super_admin)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the user was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When the user was last updated'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='When the user last logged in'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_auth0_id'), 'users', ['auth0_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth0_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###



