"""add_login_security_columns

Revision ID: f227a49caf86
Revises: merge_bba_sw_ctx
Create Date: 2026-03-05 15:28:27.784717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f227a49caf86'
down_revision = 'merge_bba_sw_ctx'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bba', 'presentation_slides',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Phase 3 presentation slide content. Contains a 'slides' array with typed slide objects (title, executive_summary, structure, recommendation, timeline, next_steps) each with an approved flag.",
               existing_comment='Phase 3 presentation slide content. Contains a slides array with typed slide objects (title, executive_summary, structure, recommendation, timeline, next_steps) each with an approved flag.',
               existing_nullable=True)
    op.alter_column('engagements', 'client_id',
               existing_type=sa.UUID(),
               comment='Foreign key to users (the client account) - kept for backward compatibility',
               existing_comment='Foreign key to users (the client account)',
               existing_nullable=True)
    op.alter_column('notes', 'read_by',
               existing_type=postgresql.ARRAY(sa.UUID()),
               comment='Array of user IDs who have read this note',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::uuid[]"))
    op.create_unique_constraint(None, 'strategy_workbooks', ['id'])
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False, comment='Number of consecutive failed login attempts'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True, comment='Account locked until this time after too many failed attempts'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_constraint(None, 'strategy_workbooks', type_='unique')
    op.alter_column('notes', 'read_by',
               existing_type=postgresql.ARRAY(sa.UUID()),
               comment=None,
               existing_comment='Array of user IDs who have read this note',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::uuid[]"))
    op.alter_column('engagements', 'client_id',
               existing_type=sa.UUID(),
               comment='Foreign key to users (the client account)',
               existing_comment='Foreign key to users (the client account) - kept for backward compatibility',
               existing_nullable=True)
    op.alter_column('bba', 'presentation_slides',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Phase 3 presentation slide content. Contains a slides array with typed slide objects (title, executive_summary, structure, recommendation, timeline, next_steps) each with an approved flag.',
               existing_comment="Phase 3 presentation slide content. Contains a 'slides' array with typed slide objects (title, executive_summary, structure, recommendation, timeline, next_steps) each with an approved flag.",
               existing_nullable=True)
    # ### end Alembic commands ###



